# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: twgZPQKEXUkxjdXHhEfwSTrIaxhdMhSX/model.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='twgZPQKEXUkxjdXHhEfwSTrIaxhdMhSX/model.proto',
  package='twgZPQKEXUkxjdXHhEfwSTrIaxhdMhSX',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n,twgZPQKEXUkxjdXHhEfwSTrIaxhdMhSX/model.proto\x12 twgZPQKEXUkxjdXHhEfwSTrIaxhdMhSX\"\x1d\n\x05\x41\x64\x64In\x12\t\n\x01x\x18\x01 \x01(\x03\x12\t\n\x01y\x18\x02 \x01(\x03\"\x17\n\x06\x41\x64\x64Out\x12\r\n\x05value\x18\x01 \x01(\x03\"\x1a\n\x07\x43ountIn\x12\x0f\n\x07strings\x18\x01 \x03(\t\"~\n\x08\x43ountOut\x12\x44\n\x05value\x18\x01 \x03(\x0b\x32\x35.twgZPQKEXUkxjdXHhEfwSTrIaxhdMhSX.CountOut.ValueEntry\x1a,\n\nValueEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x03:\x02\x38\x01\x32\xc1\x01\n\x05Model\x12X\n\x03\x61\x64\x64\x12\'.twgZPQKEXUkxjdXHhEfwSTrIaxhdMhSX.AddIn\x1a(.twgZPQKEXUkxjdXHhEfwSTrIaxhdMhSX.AddOut\x12^\n\x05\x63ount\x12).twgZPQKEXUkxjdXHhEfwSTrIaxhdMhSX.CountIn\x1a*.twgZPQKEXUkxjdXHhEfwSTrIaxhdMhSX.CountOutb\x06proto3')
)




_ADDIN = _descriptor.Descriptor(
  name='AddIn',
  full_name='twgZPQKEXUkxjdXHhEfwSTrIaxhdMhSX.AddIn',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='x', full_name='twgZPQKEXUkxjdXHhEfwSTrIaxhdMhSX.AddIn.x', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='y', full_name='twgZPQKEXUkxjdXHhEfwSTrIaxhdMhSX.AddIn.y', index=1,
      number=2, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=82,
  serialized_end=111,
)


_ADDOUT = _descriptor.Descriptor(
  name='AddOut',
  full_name='twgZPQKEXUkxjdXHhEfwSTrIaxhdMhSX.AddOut',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='value', full_name='twgZPQKEXUkxjdXHhEfwSTrIaxhdMhSX.AddOut.value', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=113,
  serialized_end=136,
)


_COUNTIN = _descriptor.Descriptor(
  name='CountIn',
  full_name='twgZPQKEXUkxjdXHhEfwSTrIaxhdMhSX.CountIn',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='strings', full_name='twgZPQKEXUkxjdXHhEfwSTrIaxhdMhSX.CountIn.strings', index=0,
      number=1, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=138,
  serialized_end=164,
)


_COUNTOUT_VALUEENTRY = _descriptor.Descriptor(
  name='ValueEntry',
  full_name='twgZPQKEXUkxjdXHhEfwSTrIaxhdMhSX.CountOut.ValueEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='twgZPQKEXUkxjdXHhEfwSTrIaxhdMhSX.CountOut.ValueEntry.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='twgZPQKEXUkxjdXHhEfwSTrIaxhdMhSX.CountOut.ValueEntry.value', index=1,
      number=2, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=_b('8\001'),
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=248,
  serialized_end=292,
)

_COUNTOUT = _descriptor.Descriptor(
  name='CountOut',
  full_name='twgZPQKEXUkxjdXHhEfwSTrIaxhdMhSX.CountOut',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='value', full_name='twgZPQKEXUkxjdXHhEfwSTrIaxhdMhSX.CountOut.value', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_COUNTOUT_VALUEENTRY, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=166,
  serialized_end=292,
)

_COUNTOUT_VALUEENTRY.containing_type = _COUNTOUT
_COUNTOUT.fields_by_name['value'].message_type = _COUNTOUT_VALUEENTRY
DESCRIPTOR.message_types_by_name['AddIn'] = _ADDIN
DESCRIPTOR.message_types_by_name['AddOut'] = _ADDOUT
DESCRIPTOR.message_types_by_name['CountIn'] = _COUNTIN
DESCRIPTOR.message_types_by_name['CountOut'] = _COUNTOUT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

AddIn = _reflection.GeneratedProtocolMessageType('AddIn', (_message.Message,), dict(
  DESCRIPTOR = _ADDIN,
  __module__ = 'twgZPQKEXUkxjdXHhEfwSTrIaxhdMhSX.model_pb2'
  # @@protoc_insertion_point(class_scope:twgZPQKEXUkxjdXHhEfwSTrIaxhdMhSX.AddIn)
  ))
_sym_db.RegisterMessage(AddIn)

AddOut = _reflection.GeneratedProtocolMessageType('AddOut', (_message.Message,), dict(
  DESCRIPTOR = _ADDOUT,
  __module__ = 'twgZPQKEXUkxjdXHhEfwSTrIaxhdMhSX.model_pb2'
  # @@protoc_insertion_point(class_scope:twgZPQKEXUkxjdXHhEfwSTrIaxhdMhSX.AddOut)
  ))
_sym_db.RegisterMessage(AddOut)

CountIn = _reflection.GeneratedProtocolMessageType('CountIn', (_message.Message,), dict(
  DESCRIPTOR = _COUNTIN,
  __module__ = 'twgZPQKEXUkxjdXHhEfwSTrIaxhdMhSX.model_pb2'
  # @@protoc_insertion_point(class_scope:twgZPQKEXUkxjdXHhEfwSTrIaxhdMhSX.CountIn)
  ))
_sym_db.RegisterMessage(CountIn)

CountOut = _reflection.GeneratedProtocolMessageType('CountOut', (_message.Message,), dict(

  ValueEntry = _reflection.GeneratedProtocolMessageType('ValueEntry', (_message.Message,), dict(
    DESCRIPTOR = _COUNTOUT_VALUEENTRY,
    __module__ = 'twgZPQKEXUkxjdXHhEfwSTrIaxhdMhSX.model_pb2'
    # @@protoc_insertion_point(class_scope:twgZPQKEXUkxjdXHhEfwSTrIaxhdMhSX.CountOut.ValueEntry)
    ))
  ,
  DESCRIPTOR = _COUNTOUT,
  __module__ = 'twgZPQKEXUkxjdXHhEfwSTrIaxhdMhSX.model_pb2'
  # @@protoc_insertion_point(class_scope:twgZPQKEXUkxjdXHhEfwSTrIaxhdMhSX.CountOut)
  ))
_sym_db.RegisterMessage(CountOut)
_sym_db.RegisterMessage(CountOut.ValueEntry)


_COUNTOUT_VALUEENTRY._options = None

_MODEL = _descriptor.ServiceDescriptor(
  name='Model',
  full_name='twgZPQKEXUkxjdXHhEfwSTrIaxhdMhSX.Model',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=295,
  serialized_end=488,
  methods=[
  _descriptor.MethodDescriptor(
    name='add',
    full_name='twgZPQKEXUkxjdXHhEfwSTrIaxhdMhSX.Model.add',
    index=0,
    containing_service=None,
    input_type=_ADDIN,
    output_type=_ADDOUT,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='count',
    full_name='twgZPQKEXUkxjdXHhEfwSTrIaxhdMhSX.Model.count',
    index=1,
    containing_service=None,
    input_type=_COUNTIN,
    output_type=_COUNTOUT,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_MODEL)

DESCRIPTOR.services_by_name['Model'] = _MODEL

# @@protoc_insertion_point(module_scope)
